import { ERROR_MESSAGES, statusForCode } from '@dp/core/api/errors'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { ApiError, callFunction, type RequestOptions } from '@/lib/api/http'
import { env } from '@/lib/env'

/**
 * The cabinet talks to Supabase as the signed-in user: reads go through PostgREST under RLS,
 * writes through owner_* SQL functions that check the role. Nothing here holds a secret;
 * this module is only loaded by the owner chunk.
 */
let client: SupabaseClient | null = null

export function supabase(): SupabaseClient {
  client ??= createClient(env.supabaseUrl, env.anonKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      // Recovery and invite links generated by the Auth admin API carry tokens in the hash.
      flowType: 'implicit',
      storageKey: 'dp-owner-auth',
    },
  })
  return client
}

interface DbError {
  message?: string
  details?: string | null
  code?: string
}

/** PostgREST / SQL errors -> ApiError with a stable code and a human message. */
export function toApiError(e: DbError | null | undefined): ApiError {
  const message = e?.message ?? ''
  if (/^[A-Z][A-Z_]+$/.test(message)) {
    // private.fail(code, human detail)
    return new ApiError(message, (e?.details && e.details !== message ? e.details : null) ?? ERROR_MESSAGES[message] ?? ERROR_MESSAGES.INTERNAL!, statusForCode(message))
  }
  if (e?.code === 'PGRST301' || e?.code === 'PGRST302' || /JWT/i.test(message)) {
    return new ApiError('UNAUTHENTICATED', 'Сессия истекла — войдите снова', 401)
  }
  if (e?.code === '23514' || e?.code === '23502' || e?.code === '22P02' || e?.code === '22007' || e?.code === '22008') {
    return new ApiError('VALIDATION', ERROR_MESSAGES.VALIDATION!, 400)
  }
  if (e?.code === '23505') return new ApiError('CONFLICT', 'Такая запись уже существует', 409)
  if (/fetch|network/i.test(message)) return new ApiError('NETWORK', ERROR_MESSAGES.NETWORK!, 0)
  return new ApiError('INTERNAL', ERROR_MESSAGES.INTERNAL!, 500)
}

export async function rpc<T>(fn: string, args: Record<string, unknown>): Promise<T> {
  const { data, error } = await supabase().rpc(fn, args)
  if (error) throw toApiError(error)
  return data as T
}

/** Awaits a PostgREST query builder and returns its rows or throws an ApiError. */
export async function rows<T>(query: PromiseLike<{ data: unknown; error: DbError | null }>): Promise<T[]> {
  const { data, error } = await query
  if (error) throw toApiError(error)
  return (data ?? []) as T[]
}

/** Edge Function call authorised as the signed-in user (owner-api). */
export async function ownerFunction<T>(path: string, o: RequestOptions = {}): Promise<T> {
  const { data } = await supabase().auth.getSession()
  const token = data.session?.access_token
  if (!token) throw new ApiError('UNAUTHENTICATED', 'Сессия истекла — войдите снова', 401)
  return callFunction<T>(`/owner-api${path}`, { ...o, headers: { ...o.headers, authorization: `Bearer ${token}` } })
}

/** E.164 from what the phone input shows ("+7 916 123-45-67" -> "+79161234567"). */
export function toE164(display: string): string | null {
  const digits = display.replace(/\D/g, '')
  return digits.length >= 8 ? `+${digits}` : null
}
