import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '.local/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'supabase/functions/_vendor/**',
      'apps/web/dev-dist/**',
      // Generated by `astryx theme build` from detailing.ts.
      'apps/web/src/theme/astryx/detailing.js',
      'apps/web/src/theme/astryx/*.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-restricted-syntax': [
        'error',
        {
          selector: "BinaryExpression[operator=/^[!=]==?$/] > Literal[value=/^(graphite|verde)$/i]",
          message: 'Tenant-specific branching is forbidden: tenants are data, not code.',
        },
      ],
    },
  },
  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  {
    files: ['supabase/functions/**/*.ts', 'scripts/dev/gateway.ts'],
    languageOptions: {
      globals: { Deno: 'readonly' },
    },
  },
)
