/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/astryx/detailing.ts
 * Command: astryx theme build src/theme/astryx/detailing.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./detailing.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const detailingTheme: DefinedTheme;
